### PR TITLE
Minor Corrections (July 16 2024)

### PR DESCRIPTION
**Pull request by jmscarlett**
Minor corrections of issues like author affiliations and incorrect URLs in PDF files.

### CODE REVIEW

**Review by lawrennd — APPROVED** [review]
Changes to PDFs by publications editor.

**Comment by lawrennd** [comment]
Hi John, These changes need to be merged into main rather than gh-pages (due to new format).

**Comment by jmscarlett** [comment]
Sorry, I selected 'main' on GitHub Desktop but somehow got to 'gh-pages' in the browser.  I have changed it to 'main' in the browser now -- is that all I need to do?

**Review by lawrennd — APPROVED** [review]
PDF changes from publication editor.

**Pull request merged**
