### PR TITLE
Update 2024-07-08-theo24a.md

### PR DESCRIPTION
**Pull request by TheoGuyard**
I think there has been a switch between by first and last names. I'm don't know if it's also possible to update the bib ref theo24a to guyard24a ?

### CODE REVIEW

**Comment by jmscarlett** [comment]
Note from publication chair: I approve this change, but I'm not sure about the rename to guyard24a (will let PMLR decide)

**Review by lawrennd — APPROVED** [review]
Changes looks fine, thanks for fixing.

**Comment by lawrennd** [comment]
Thanks, I'll update the file links and keys too.

**Comment by lawrennd** [comment]
Changed key names as well. Thanks for the fixes.

**Pull request merged**
